---
title: "Reputation penalty - study 3, survey 2"
author: "Jacob Ausubel, Annika Davies, and Ethan Porter"
date: "2025-01-16"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Study 3, survey 2

```{r, include = FALSE, message = FALSE}
#Clear global environment
rm(list = ls())
```

```{r, include = FALSE, message = FALSE}
#Loading various packages
library(readr)
library(lmtest)
library(sandwich)
library(margins)
library(texreg)
library(haven)
library(MASS)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(marginaleffects)
library(estimatr)
library(imputeTS)
library(fabricatr)
library(tidyr)
library(tidyverse)
library(lubridate)
library(qualtRics)
library(naniar)
library(RCT)
library(texreg)
library(huxtable)
library(stargazer)
library(ggpubr)
library(vtable)
library(cobalt)
library(kableExtra)
library(xtable)
library(ggthemes)
library(stats)
library(pwr)
library(WebPower)
library(effectsize)
library(TOSTER)
```

```{r, include = FALSE, message = FALSE}
#Read in data
#abortion_s3_private <- read_csv("Abortion Study 3 Wave 2_July 11, 2024_14.13.csv")
```

```{r, include = FALSE, message = FALSE}
#Renaming one variable
#abortion_s3_private <-
#  abortion_s3_private %>%
#  rename(Q1_125 = Q1...125)
```


```{r, include = FALSE, message = FALSE}
#Filter to just respondents with IP Addresses
#Remove personally identifying information
#abortion_s3_public <-
#  abortion_s3_private %>%
#  filter(Status == "IP Address") %>%
#  select(-c(Status, IPAddress, ResponseId, RecipientLastName, RecipientFirstName, RecipientEmail, 
#            ExternalReference, LocationLatitude, LocationLongitude, DistributionChannel, Q2_Browser, 
#            `Q2_Operating System`, Q2_Resolution, assignmentId, participantId, projectId,
#            state, zip))
```

```{r, include = FALSE, message = FALSE}
#Creating public CSV file
#write.csv(abortion_s3_public, "Abortion Study 3 Wave 2_July 11, 2024_14.13 - PUBLIC.csv", row.names = FALSE)
```

```{r, include = FALSE, message = FALSE}
#Clear global environment
rm(list = ls())
```

```{r, include = FALSE, message = FALSE}
#Reading in public data
abortion_s3_cleaned <- read_csv("Abortion Study 3 Wave 2_July 11, 2024_14.13 - PUBLIC.csv")
```

```{r, include = FALSE, message = FALSE}
#Filtering to people who pass both attention checks
abortion_s3_cleaned$ac1 <- trimws(abortion_s3_cleaned$ac1)
abortion_s3_cleaned_v2 <-
  abortion_s3_cleaned %>%
  #filter(Status == "IP Address") %>%
  filter(ac1 %in%
    c("Talked on the telephone",
      "Watched television",
      "Watched television,Talked on the telephone",
      "Watched television,Talked on the telephone,None of these")) %>%
  filter(ac2 == "Extremely interested,Very interested")
```

```{r, include = FALSE, message = FALSE}
#Creating Gruber condition variable
abortion_s3_cleaned_v2$gruber_condition <- NA
abortion_s3_cleaned_v2$gruber_condition[
  abortion_s3_cleaned_v2$FL_80_DO == "FL_112"
  ] <- "misinfo"
abortion_s3_cleaned_v2$gruber_condition[
  abortion_s3_cleaned_v2$FL_80_DO == "FL_88"
  ] <- "fc"
abortion_s3_cleaned_v2$gruber_condition[
  abortion_s3_cleaned_v2$FL_80_DO == "FL_89"
  ] <- "control"
```

```{r, include = FALSE, message = FALSE}
#Creating Shapiro condition variable
abortion_s3_cleaned_v2$shapiro_condition <- NA
abortion_s3_cleaned_v2$shapiro_condition[
  abortion_s3_cleaned_v2$FL_80_DO == "FL_111"
  ] <- "misinfo"
abortion_s3_cleaned_v2$shapiro_condition[
  abortion_s3_cleaned_v2$FL_80_DO == "FL_83"
  ] <- "fc"
abortion_s3_cleaned_v2$shapiro_condition[
  abortion_s3_cleaned_v2$FL_80_DO == "FL_85"
  ] <- "control"
```

```{r, include = FALSE, message = FALSE}
#Recoding partisanship
abortion_s3_cleaned_v2$pid7 <- NA
abortion_s3_cleaned_v2$pid7[
  abortion_s3_cleaned_v2$pid_dem == "Strong Democrat"
  ] <- 1
abortion_s3_cleaned_v2$pid7[
  abortion_s3_cleaned_v2$pid_dem == "Not very strong Democrat"
  ] <- 2
abortion_s3_cleaned_v2$pid7[
  abortion_s3_cleaned_v2$pid_indep == "Closer to the Democratic Party"
  ] <- 3
abortion_s3_cleaned_v2$pid7[
  abortion_s3_cleaned_v2$pid_indep == "Neither"
  ] <- 4
abortion_s3_cleaned_v2$pid7[
  abortion_s3_cleaned_v2$pid_indep == "Closer to the Republican Party"
  ] <- 5
abortion_s3_cleaned_v2$pid7[
  abortion_s3_cleaned_v2$pid_rep == "Not very strong Republican"
  ] <- 6
abortion_s3_cleaned_v2$pid7[
  abortion_s3_cleaned_v2$pid_rep == "Strong Republican"
  ] <- 7
```

```{r, include = FALSE, message = FALSE}
#Recoding gender
abortion_s3_cleaned_v2$male <-
  ifelse(abortion_s3_cleaned_v2$gender == "Man", 1, 0)
```

```{r, include = FALSE, message = FALSE}
#Recoding age
abortion_s3_cleaned_v2$age <-
  2024 - as.numeric(abortion_s3_cleaned_v2$birthyear)
```

```{r, include = FALSE, message = FALSE}
#Recoding religiosity
abortion_s3_cleaned_v2$monthly_attend <-
  ifelse(abortion_s3_cleaned_v2$religiosity %in% 
    c("More than once a week", "Once a week", "Once or twice a month"), 1, 0)
```

```{r, include = FALSE, message = FALSE}
#Recoding education
abortion_s3_cleaned_v2$college_grad <-
  ifelse(abortion_s3_cleaned_v2$educ %in%
    c("Bachelor's degree", "Master's degree", "Professional or doctorate degree"), 1, 0)
```

```{r, include = FALSE, message = FALSE}
#Recoding race/ethnicity
abortion_s3_cleaned_v2$white_non_hisp <-
  ifelse(abortion_s3_cleaned_v2$race == "White" & abortion_s3_cleaned_v2$hispanic == "No", 1, 0)
```

```{r, include = FALSE, message = FALSE}
#Recoding religion
abortion_s3_cleaned_v2$relig_unaff <-
  ifelse(abortion_s3_cleaned_v2$religion %in%
    c("Agnostic", "Atheist", "Nothing in particular"), 1, 0)
```

```{r, include = FALSE, message = FALSE}
#Recoding income
abortion_s3_cleaned_v2$high_income <-
  ifelse(abortion_s3_cleaned_v2$income %in% c("$100,000 to less than $200,000",
      "$200,000 to less than $250,000",
      "Greater than $250,000"), 1, 0)
```

```{r, include = FALSE, message = FALSE}
#Creating smaller subsets of data
gruber_s3 <-
  abortion_s3_cleaned_v2 %>%
  filter(!is.na(gruber_condition))
shapiro_s3 <-
  abortion_s3_cleaned_v2 %>%
  filter(!is.na(shapiro_condition))
```

```{r, include = FALSE, message = FALSE}
#Creating Gruber feeling thermometer variable
gruber_s3$ft_gruber <- NA
gruber_s3$ft_gruber[
  !(is.na(gruber_s3$Q92_1))
  ] <- gruber_s3$Q92_1[
  !(is.na(gruber_s3$Q92_1))]
gruber_s3$ft_gruber[
  !(is.na(gruber_s3$Q1_1))
  ] <- gruber_s3$Q1_1[
  !(is.na(gruber_s3$Q1_1))]
gruber_s3$ft_gruber[
  !(is.na(gruber_s3$Q137_1))
  ] <- gruber_s3$Q137_1[
  !(is.na(gruber_s3$Q137_1))]
gruber_s3$ft_gruber <-
  as.numeric(gruber_s3$ft_gruber)
```

```{r, include = FALSE, message = FALSE}
#Setting misinformation as reference category
gruber_s3$gruber_condition <- factor(gruber_s3$gruber_condition)
gruber_s3$gruber_condition <-
  relevel(gruber_s3$gruber_condition, ref = "misinfo")
```

```{r, include = FALSE, message = FALSE}
#Creating Shapiro feeling thermometer variable
shapiro_s3$ft_shapiro <- NA
shapiro_s3$ft_shapiro[
  !(is.na(shapiro_s3$Q110_1))
  ] <- shapiro_s3$Q110_1[
  !(is.na(shapiro_s3$Q110_1))]
shapiro_s3$ft_shapiro[
  !(is.na(shapiro_s3$Q74_1))
  ] <- shapiro_s3$Q74_1[
  !(is.na(shapiro_s3$Q74_1))]
shapiro_s3$ft_shapiro[
  !(is.na(shapiro_s3$Q128_1))
  ] <- shapiro_s3$Q128_1[
  !(is.na(shapiro_s3$Q128_1))]
shapiro_s3$ft_shapiro <-
  as.numeric(shapiro_s3$ft_shapiro)
```

```{r, include = FALSE, message = FALSE}
#Setting misinformation as reference category
shapiro_s3$shapiro_condition <- factor(shapiro_s3$shapiro_condition)
shapiro_s3$shapiro_condition <-
  relevel(shapiro_s3$shapiro_condition, ref = "misinfo")
```

## Attitudinal models


```{r, include = FALSE, message = FALSE}
#Creating new ft_activist and condition variables (so that Gruber
  #and Shapiro can be compared more easily in the same regression table)
gruber_s3$ft_activist <- gruber_s3$ft_gruber
gruber_s3$condition <- gruber_s3$gruber_condition

shapiro_s3$ft_activist <- shapiro_s3$ft_shapiro
shapiro_s3$condition <- shapiro_s3$shapiro_condition
```

```{r, include = FALSE, message = FALSE}
#Running models

#Seth Gruber
fit1_s3 <- lm_robust(ft_activist ~ condition + pid7 + male + age + 
  monthly_attend + college_grad + white_non_hisp + relig_unaff, data = gruber_s3)
#Ben Shapiro
fit2_s3 <- lm_robust(ft_activist ~ condition + pid7 + male + age + 
  monthly_attend + college_grad + white_non_hisp + relig_unaff, data = shapiro_s3)
```

```{r, echo = FALSE, results='asis'}
#Creating regression table
texreg(list(fit1_s3, fit2_s3),
  include.ci = FALSE,
  custom.coef.names = 
    c("Intercept", "Control", "Fact check", "Partisanship (1-to-7)",
      "Male", "Age", "Monthly attendance", "College grad", "White non-Hispanic", "Religiously unaffiliated"),
  caption = "Model predicting feelings (0-to-100 scale) toward the activist falsely claiming that more contraception availability increases abortion demand",
  custom.model.names = c("Seth Gruber", "Ben Shapiro"),
  caption.above = TRUE, float.pos = "H",
  single.row = TRUE,
       omit.coef = "pid7|male|age|monthly_attend|college_grad|white_non_hisp|relig_unaff")
```

## Creating attitudinal beliefs graph

```{r, include = FALSE, warning = FALSE}
#Making predictions for average feeling thermometer ratings for Gruber
  #when in control, misinformation, and fact-check conditions
gruber_data_control <- data.frame(
  condition = factor("control", levels = levels(gruber_s3$condition)), 
  pid7 = mean(gruber_s3$pid7, na.rm = T),
  male = mean(gruber_s3$male, na.rm = T),
  age = mean(gruber_s3$age, na.rm = T),
  monthly_attend = mean(gruber_s3$monthly_attend, na.rm = T),
  college_grad = mean(gruber_s3$college_grad, na.rm = T),
  white_non_hisp = mean(gruber_s3$white_non_hisp, na.rm = T),
  relig_unaff = mean(gruber_s3$relig_unaff, na.rm = T)
)

gruber_data_misinfo <- data.frame(
  condition = factor("misinfo", levels = levels(gruber_s3$condition)), 
  pid7 = mean(gruber_s3$pid7, na.rm = T),
  male = mean(gruber_s3$male, na.rm = T),
  age = mean(gruber_s3$age, na.rm = T),
  monthly_attend = mean(gruber_s3$monthly_attend, na.rm = T),
  college_grad = mean(gruber_s3$college_grad, na.rm = T),
  white_non_hisp = mean(gruber_s3$white_non_hisp, na.rm = T),
  relig_unaff = mean(gruber_s3$relig_unaff, na.rm = T)
)

gruber_data_fc <- data.frame(
  condition = factor("fc", levels = levels(gruber_s3$condition)),
  pid7 = mean(gruber_s3$pid7, na.rm = T),
  male = mean(gruber_s3$male, na.rm = T),
  age = mean(gruber_s3$age, na.rm = T),
  monthly_attend = mean(gruber_s3$monthly_attend, na.rm = T),
  college_grad = mean(gruber_s3$college_grad, na.rm = T),
  white_non_hisp = mean(gruber_s3$white_non_hisp, na.rm = T),
  relig_unaff = mean(gruber_s3$relig_unaff, na.rm = T)
)

# Make predictions
gruber_predictions_control <- 
  predict(fit1_s3, newdata = gruber_data_control, se.fit = TRUE)
gruber_predictions_misinfo <- 
  predict(fit1_s3, newdata = gruber_data_misinfo, se.fit = TRUE)
gruber_predictions_fc <- 
  predict(fit1_s3, newdata = gruber_data_fc, se.fit = TRUE)
```


```{r, include = FALSE, warning = FALSE}
#Making predictions for average feeling thermometer ratings for Shapiro
  #when in control, misinformation, and fact-check conditions
shapiro_data_control <- data.frame(
  condition = factor("control", levels = levels(shapiro_s3$condition)), 
  pid7 = mean(shapiro_s3$pid7, na.rm = T),
  male = mean(shapiro_s3$male, na.rm = T),
  age = mean(shapiro_s3$age, na.rm = T),
  monthly_attend = mean(shapiro_s3$monthly_attend, na.rm = T),
  college_grad = mean(shapiro_s3$college_grad, na.rm = T),
  white_non_hisp = mean(shapiro_s3$white_non_hisp, na.rm = T),
  relig_unaff = mean(shapiro_s3$relig_unaff, na.rm = T)
)

shapiro_data_misinfo <- data.frame(
  condition = factor("misinfo", levels = levels(shapiro_s3$condition)), 
  pid7 = mean(shapiro_s3$pid7, na.rm = T),
  male = mean(shapiro_s3$male, na.rm = T),
  age = mean(shapiro_s3$age, na.rm = T),
  monthly_attend = mean(shapiro_s3$monthly_attend, na.rm = T),
  college_grad = mean(shapiro_s3$college_grad, na.rm = T),
  white_non_hisp = mean(shapiro_s3$white_non_hisp, na.rm = T),
  relig_unaff = mean(shapiro_s3$relig_unaff, na.rm = T)
)

shapiro_data_fc <- data.frame(
  condition = factor("fc", levels = levels(shapiro_s3$condition)),
  pid7 = mean(shapiro_s3$pid7, na.rm = T),
  male = mean(shapiro_s3$male, na.rm = T),
  age = mean(shapiro_s3$age, na.rm = T),
  monthly_attend = mean(shapiro_s3$monthly_attend, na.rm = T),
  college_grad = mean(shapiro_s3$college_grad, na.rm = T),
  white_non_hisp = mean(shapiro_s3$white_non_hisp, na.rm = T),
  relig_unaff = mean(shapiro_s3$relig_unaff, na.rm = T)
)

# Make predictions
shapiro_predictions_control <- 
  predict(fit2_s3, newdata = shapiro_data_control, se.fit = TRUE)
shapiro_predictions_misinfo <- 
  predict(fit2_s3, newdata = shapiro_data_misinfo, se.fit = TRUE)
shapiro_predictions_fc <- 
  predict(fit2_s3, newdata = shapiro_data_fc, se.fit = TRUE)
```

```{r, include = FALSE, warning = FALSE}
#Making a data frame with predicted average feeling thermometer ratings for
  #Gruber and Shapiro in various conditions
#Includes 95% confidence intervals
df_s3 <- data.frame(
  average_value = rep(NA, 6),  
  standard_error = rep(NA, 6),   
  activist = c(rep("Gruber",3), rep("Shapiro",3)),
  condition = rep(c("Control", "Misinformation", "Fact-check"),2)
)

df_s3[1,1] <-
  gruber_predictions_control[[1]][[1]]
df_s3[1,2] <-
  gruber_predictions_control[[2]][[1]]
df_s3[2,1] <-
  gruber_predictions_misinfo[[1]][[1]]
df_s3[2,2] <-
  gruber_predictions_misinfo[[2]][[1]]
df_s3[3,1] <-
  gruber_predictions_fc[[1]][[1]]
df_s3[3,2] <-
  gruber_predictions_fc[[2]][[1]]
df_s3[4,1] <-
  shapiro_predictions_control[[1]][[1]]
df_s3[4,2] <-
  shapiro_predictions_control[[2]][[1]]
df_s3[5,1] <-
  shapiro_predictions_misinfo[[1]][[1]]
df_s3[5,2] <-
  shapiro_predictions_misinfo[[2]][[1]]
df_s3[6,1] <-
  shapiro_predictions_fc[[1]][[1]]
df_s3[6,2] <-
  shapiro_predictions_fc[[2]][[1]]

#Computing 95% confidence intervals
df_s3$upper <-
  df_s3$average_value+1.96*df_s3$standard_error
df_s3$lower <-
  df_s3$average_value-1.96*df_s3$standard_error

#Renaming condition variable
df_s3 <-
  df_s3 %>%
  rename(Condition = condition)
```

```{r, include = FALSE, warning = FALSE}
#Creating a new version of the data frame that filters out the Control condition
df_s3_v2 <-
  df_s3 %>%
  filter(Condition != "Control")
```


```{r, include = FALSE, warning = FALSE}
#Creating a new variable that will allow us to position points on the graph that
  #is about to be created
df_s3_v2$var <- NULL
df_s3_v2$var[
  df_s3_v2$activist == "Gruber" & 
    df_s3_v2$Condition == "Misinformation"] <-
  1.1
df_s3_v2$var[
  df_s3_v2$activist == "Gruber" & 
    df_s3_v2$Condition == "Fact-check"] <-
  1.11
df_s3_v2$var[
  df_s3_v2$activist == "Shapiro" & 
    df_s3_v2$Condition == "Misinformation"] <-
  1.19
df_s3_v2$var[
  df_s3_v2$activist == "Shapiro" & 
    df_s3_v2$Condition == "Fact-check"] <-
  1.2
```


```{r, echo = FALSE, warning = FALSE, message = FALSE}
#Creating a graph that visualizes the effect of the fact-check on feeling thermometer
  #ratings of Gruber + Shapiro
df_s3_v2 %>%
  ggplot(aes(x=average_value, y=var, color = Condition)) +
  geom_point() +
  geom_segment(aes(y = var, x = lower, yend = var, xend = upper)) +
  scale_y_continuous(breaks=c(1.105,1.195), 
      labels=c("Seth Gruber",
               "Ben Shapiro"),
      limits = c(1.09, 1.22)) +
  ylab("Political activist") +
  xlab("Average feeling thermometer rating") +
  scale_color_manual(
    values = c(
      "Misinformation" = "red",
      "Fact-check" = "blue"
    )) +
  theme_classic() +
  #Adding line segments and text that makes it easier to visualize the effect of
    #the fact-checks on feeling thermometer ratings of Gruber + Shapiro
  geom_segment(x = 28.60955, xend = 28.60955, y = 1.19, 
    yend = 1.21, color = "black") +
  geom_segment(x = 28.52849, xend = 28.52849, y = 1.2, 
    yend = 1.21, color = "black") +
  geom_segment(x = 28.52849, xend = 28.60955, y = 1.21, 
    yend = 1.21, color = "black") +
  geom_text(aes(x = 28.56902, y = 1.211, label = "-0.08 (p > 0.05)"), color = "black", size = 4, vjust = -1) +
  geom_segment(x = 38.80975, xend = 38.80975, y = 1.1, 
    yend = 1.12, color = "black") +
  geom_segment(x = 33.19139, xend = 33.19139, y = 1.11, 
    yend = 1.12, color = "black") +
  geom_segment(x = 33.19139, xend = 38.80975, y = 1.12, 
    yend = 1.12, color = "black") +
  geom_text(aes(x = 36, y = 1.12, label = "-5.62 (p < 0.001)"), color = "black", size = 4, vjust = -1)
```

## Factual beliefs models

```{r, include = FALSE, message = FALSE}
#Creating name recognition variable
gruber_s3$recognition <- "Low"
shapiro_s3$recognition <- "High"
```

```{r, include = FALSE, message = FALSE}
#Combining into single data frame again
abortion_s3_cleaned_v3 <-
  bind_rows(gruber_s3, shapiro_s3)
```

```{r message=FALSE, include=FALSE}
#Creating factual beliefs variable (regardless of 
  #which condition in and whether asked about
  #Gruber or Shapiro)
abortion_s3_cleaned_v3$factual_belief <- NA
abortion_s3_cleaned_v3$factual_belief[
  !(is.na(abortion_s3_cleaned_v3$Q91))] <-
  abortion_s3_cleaned_v3$Q91[
  !(is.na(abortion_s3_cleaned_v3$Q91))  
  ]
abortion_s3_cleaned_v3$factual_belief[
  !(is.na(abortion_s3_cleaned_v3$Q109))] <-
  abortion_s3_cleaned_v3$Q109[
  !(is.na(abortion_s3_cleaned_v3$Q109))  
  ]
abortion_s3_cleaned_v3$factual_belief[
  !(is.na(abortion_s3_cleaned_v3$Q127))] <-
  abortion_s3_cleaned_v3$Q127[
  !(is.na(abortion_s3_cleaned_v3$Q127))  
  ]
abortion_s3_cleaned_v3$factual_belief[
  !(is.na(abortion_s3_cleaned_v3$Q1_125))] <-
  abortion_s3_cleaned_v3$Q1_125[
  !(is.na(abortion_s3_cleaned_v3$Q1_125))  
  ]
abortion_s3_cleaned_v3$factual_belief[
  !(is.na(abortion_s3_cleaned_v3$Q136))] <-
  abortion_s3_cleaned_v3$Q136[
  !(is.na(abortion_s3_cleaned_v3$Q136))  
  ]
abortion_s3_cleaned_v3$factual_belief[
  !(is.na(abortion_s3_cleaned_v3$Q73))] <-
  abortion_s3_cleaned_v3$Q73[
  !(is.na(abortion_s3_cleaned_v3$Q73))  
  ]
```

```{r, include = FALSE, message = FALSE}
#Recoding factual beliefs
abortion_s3_cleaned_v3$factual_belief_v2 <- NA
abortion_s3_cleaned_v3$factual_belief_v2[
  abortion_s3_cleaned_v3$factual_belief == "Not at all accurate"
  ] <- 1
abortion_s3_cleaned_v3$factual_belief_v2[
  abortion_s3_cleaned_v3$factual_belief == "Not very accurate"
  ] <- 2
abortion_s3_cleaned_v3$factual_belief_v2[
  abortion_s3_cleaned_v3$factual_belief == "Somewhat accurate"
  ] <- 3
abortion_s3_cleaned_v3$factual_belief_v2[
  abortion_s3_cleaned_v3$factual_belief == "Very accurate"
  ] <- 4
```

```{r, include = FALSE, message = FALSE}
#Creating control condition and fact-check condition variables
abortion_s3_cleaned_v3$control_condition <-
  ifelse(abortion_s3_cleaned_v3$condition == "control", 1, 0)
abortion_s3_cleaned_v3$fc_condition <-
  ifelse(abortion_s3_cleaned_v3$condition == "fc", 1, 0)
```

```{r, include = FALSE, warning = FALSE}
#Running Gruber model
fit5_s3 <- lm_robust(factual_belief_v2 ~ control_condition + 
  fc_condition + pid7 + male + age + 
  monthly_attend + college_grad + white_non_hisp + relig_unaff, 
  data = subset(abortion_s3_cleaned_v3, recognition == "Low"))
#Running Shapiro model
fit6_s3 <- lm_robust(factual_belief_v2 ~ control_condition + 
  fc_condition + pid7 + male + age + 
  monthly_attend + college_grad + white_non_hisp + relig_unaff, 
  data = subset(abortion_s3_cleaned_v3, recognition == "High"))
```

```{r, echo = FALSE, results='asis'}
#Creating regression table
texreg(list(fit5_s3, fit6_s3),
  include.ci = FALSE,
  custom.coef.names = 
    c("Intercept", "Control", "Fact check", "Partisanship (1-to-7)",
      "Male", "Age", "Monthly attendance", "College grad", "White non-Hispanic", "Religiously unaffiliated"),
  caption = "Effect of fact check on the belief that more contraception availability increases abortion demand (1-to-4 scale), broken down by the activist who spread the misinformation", 
  custom.model.names = c("Seth Gruber", "Ben Shapiro"),
  caption.above = TRUE, float.pos = "H",
  single.row = TRUE,
       omit.coef = "pid7|male|age|monthly_attend|college_grad|white_non_hisp|relig_unaff")
```

\newpage

## Balance table

```{r, include = FALSE, warning = FALSE}
#Recoding condition variable
abortion_s3_cleaned_v3$condition_v2 <- NA
abortion_s3_cleaned_v3$condition_v2[
  abortion_s3_cleaned_v3$condition == "misinfo"
  ] <- "misinformation"
abortion_s3_cleaned_v3$condition_v2[
  abortion_s3_cleaned_v3$condition == "control"
  ] <- "control"
abortion_s3_cleaned_v3$condition_v2[
  abortion_s3_cleaned_v3$condition == "fc"
  ] <- "factcheck"
```


```{r, include = FALSE, warning = FALSE}
#Recoding income variable
abortion_s3_cleaned_v3$income_100000 <-
  ifelse(abortion_s3_cleaned_v3$income %in% 
    c("$100,000 to less than $200,000",
      "$200,000 to less than $250,000",
      "Greater than $250,000"),1,0)
```

```{r, include = FALSE, warning = FALSE}
#Recoding age variable
abortion_s3_cleaned_v3$age[
  abortion_s3_cleaned_v3$age < 18
  ] <- NA
abortion_s3_cleaned_v3$age[
  abortion_s3_cleaned_v3$age > 100
  ] <- NA
```


```{r, include = FALSE, warning = FALSE}
#Selecting just some variables and restricting analysis to Gruber rows
abortion_gruber_s3 <-
  abortion_s3_cleaned_v3 %>%
  dplyr::select(recognition, condition_v2,
    age, pid7, male, white_non_hisp,
    college_grad, income_100000) %>%
  filter(recognition == "Low") %>%
  dplyr::select(-recognition)
```

```{r, include = FALSE, warning = FALSE}
#Selecting just some variables and restricting analysis to Shapiro rows
abortion_shapiro_s3 <-
  abortion_s3_cleaned_v3 %>%
  dplyr::select(recognition, condition_v2,
    age, pid7, male, white_non_hisp,
    college_grad, income_100000) %>%
  filter(recognition == "High") %>%
  dplyr::select(-recognition)
```

Gruber:

```{r, include = FALSE, warning = FALSE}
#Renaming column names
colnames(abortion_gruber_s3) <-
  c("Condition", "Age", 
    "Partisanship (7-point scale)",
    "Share who are male", 
    "Share who are non-Hispanic White", 
    "Share who are college graduates", 
    "Share who have household incomes of $100,000+"
    )
#Recoding condition variable
abortion_gruber_s3$Condition[
  abortion_gruber_s3$Condition == "control"
  ] <- "Control"
abortion_gruber_s3$Condition[
  abortion_gruber_s3$Condition == "factcheck"
  ] <- "Fact-check"
abortion_gruber_s3$Condition[
  abortion_gruber_s3$Condition == "misinformation"
  ] <- "Misinformation"
```


```{r, include = FALSE, warning = FALSE}
#Setting up balance table
abortion_gruber_bt_s3 <- balance_table(abortion_gruber_s3, "Condition")
colnames(abortion_gruber_bt_s3) <- 
  c("Variable", "Control", "Fact check", "Misinfo", "p-value (c vs fc)", "p-value (c vs mis)")
```

```{r, echo = FALSE, results='asis'}
#Printing out Gruber balance table
print(xtable(abortion_gruber_bt_s3), size = "tiny")
```

Shapiro:

```{r, include = FALSE, warning = FALSE}
#Renaming column names
colnames(abortion_shapiro_s3) <-
  c("Condition", "Age", 
    "Partisanship (7-point scale)",
    "Share who are male", 
    "Share who are non-Hispanic White", 
    "Share who are college graduates", 
    "Share who have household incomes of $100,000+"
    )
#Recoding condition variable
abortion_shapiro_s3$Condition[
  abortion_shapiro_s3$Condition == "control"
  ] <- "Control"
abortion_shapiro_s3$Condition[
  abortion_shapiro_s3$Condition == "factcheck"
  ] <- "Fact-check"
abortion_shapiro_s3$Condition[
  abortion_shapiro_s3$Condition == "misinformation"
  ] <- "Misinformation"
```

```{r, include = FALSE, warning = FALSE}
#Setting up balance table
abortion_shapiro_bt_s3 <- balance_table(abortion_shapiro_s3, "Condition")
colnames(abortion_shapiro_bt_s3) <- 
  c("Variable", "Control", "Fact check", "Misinfo", "p-value (c vs fc)", "p-value (c vs mis)")
```

```{r, echo = FALSE, results='asis'}
#Printing out balance table
print(xtable(abortion_shapiro_bt_s3), size = "tiny")
```
